### ISSUE TITLE
I can't access or fork this?

### ISSUE THREAD

**Issue by carolinesoleelee** [learn-co-curriculum/translating-orm-to-ar#3] opened 2018-10-21 23:39 UTC
It's saying that I dont have permission and I high dont think that should be the case

**Comment by maxwellbenton** [comment] 2018-10-23 16:23
Thank you for spotting this and providing feedback, @carolinesoleelee.

This issue occurred for multiple students over the past day or so and we believe it was caused by an outage on GitHub (https://www.onmsft.com/news/github-suffers-hours-long-outage-coming-back-online-now). As of now, this lesson is correctly forking and submitting, so I am going to close this issue for now.

If you are still unable to fork this lesson, please re-open this issue. 💙

**Closed as completed by maxwellbenton** 2018-10-23 16:23 UTC
Labels: Curriculum
